kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: &PostgreSQLLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-server
spec:
  replicas: 1
  selector:
    matchLabels: *PostgreSQLLabels
  serviceName: {{ .Release.Name }}-postgresql-service
  template:
    metadata:
      labels: *PostgreSQLLabels
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      volumes:
      - name: {{ .Release.Name }}-postgresql-pvc
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgresql-pvc
      containers:
      - name: postgresql-server
        image: {{ .Values.postgresql.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username=$POSTGRES_USER
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username=$POSTGRES_USER
          initialDelaySeconds: 25
          timeoutSeconds: 3
          periodSeconds: 5
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: {{ .Release.Name }}-postgresql-pvc
          mountPath: /var/lib/postgresql/data
        env:
        - name: "PGDATA"
          value: "/var/lib/postgresql/data/pgdata"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: password
        - name: "POSTGRES_USER" 
          value: {{.Values.postgresql.db.user}}
        - name: "POSTGRES_DB"
          value: {{.Values.postgresql.db.name}}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "HOST"
          value: "{{ .Release.Name }}-postgresql-service"
