unleash:
  image:
    repo: gcr.io/bricks-software-public/unleash-enterprise
    tag: latest
postgresql:
  image: gcr.io/bricks-software-public/postgresql11:latest
  exporter:
    image: null
  db:
    password: null
    name: unleash
    user: unleash
metrics:
  image: gcr.io/bricks-software-public/prometheus-to-sd:0.9.2
  exporter:
    enabled: flalse
deployer:
  image: null
